### ISSUE TITLE
bug running get_sim_data

### ISSUE THREAD

**Issue by goroda** [gorodetsky-umich/simulateTestCases#34]
Executing 
```
from simulateTestCases.run_sim import run_sim
from simulateTestCases.utils import get_sim_data


if __name__ == "__main__":

    info_file = 'examples/inputs/naca0012_simInfo.yaml'
    # sim = run_sim(info_file)

    # sim.run()

    # sim.post_process()

    sim_data = get_sim_data(info_file, 0)

    print(sim_data)
```

Recieved the following error

```
Traceback (most recent call last):
  File "/home/mdolabuser/mount/test_simulate_cases/main.py", line 14, in <module>
    sim_data = get_sim_data(info_file, 0)
  File "/home/mdolabuser/mount/simulateTestCases/simulateTestCases/utils.py", line 39, in get_sim_data
    sim_info = load_yaml_file(f"{info['out_dir']}/overall_sim_info.yaml")
TypeError: load_yaml_file() missing 1 required positional argument: 'comm'
```

**Comment by sinaendhran** [comment]
Rectified in utils.py and tested
